function [T, S, I, QVg, QTg, QSg, QVs, QTs, QSs,...
    QVk, QTk, QSk, QVmi, QTmi, QSmi,QIi,QTi,QSi,...
    QVv,QTv,QSv,Te,Se, phi, M] = preallocate_zmodel_variables(p, f, t)

[T, S, I] = deal(zeros(p.N, length(t)));

[QVg,QTg,QSg,...
    QVs,QTs,QSs,...
    QVk,QTk,QSk,...
    QVmi,QTmi,QSmi,...
    QIi,QTi,QSi,...
    QVv,QTv,QSv,...
    Te,Se, phi] = deal(zeros(p.N,length(t)-1));

M = zeros(length(f.zi),length(t)-1);

end